from YUI import (DEV_USERS, DRAGONS, DEMONS, TIGERS, WOLVES, telethn)

Zoro = [1936119750]

IMMUNE_USERS = DRAGONS + WOLVES + DEMONS + TIGERS + DEV_USERS + ISHIKKI

IMMUNE_USERS = list(DRAGONS) + list(WOLVES) + list(DEMONS) + list(
    TIGERS) + list(DEV_USERS) + list(Zoro)
